DX-2243 Update Machine Detection Model Name
Bandwidth/ruby-sdk pull request #31
Opened 2021-09-27 18:12 UTC by ajrice6713

2021-09-27 19:07 UTC, ckoegel approved these changes

2021-09-27 19:24 UTC, hamermike requested changes

2021-09-27 19:24 UTC, hamermike commented on lib/bandwidth/voice_lib/voice/models/machine_detection_configuration.rb
> +  # MachineDetectionRequest Model.
```suggestion
  # MachineDetectionConfiguration Model.
```

2021-09-27 21:07 UTC, hamermike approved these changes

2021-09-28 13:12 UTC, ckoegel approved these changes

2021-09-28 13:17 UTC, merged